export const Offer = [
  {
    id:1,
    img:"https://www.sparindia.com/_next/image?url=https%3A%2F%2Fmcprod.sparindia.com%2Fmedia%2F%2Fwysiwyg%2Fjune-theme%2Fmobile%2FSugar_3x.png&w=1920&q=100"
  },
  {
    id:2,
    img:"https://www.sparindia.com/_next/image?url=https%3A%2F%2Fmcprod.sparindia.com%2Fmedia%2F%2Fwysiwyg%2Fjune-theme%2Fbanners%2FKitchen_Cookware_3x_1_.png&w=1920&q=100",
  }
  ,{
    id:3,
    img:"https://www.sparindia.com/_next/image?url=https%3A%2F%2Fmcprod.sparindia.com%2Fmedia%2F%2Fwysiwyg%2Fjune-theme%2Fmobile%2Fonion_3x_1_.png&w=1920&q=100",
  }
]

export const subCatImages = [
    {
      key:1,
      img: "https://www.sparindia.com/_next/image?url=https%3A%2F%2Fmcprod.sparindia.com%2Fmedia%2Fwysiwyg%2Fjune-theme%2Fmobile%2FSnacks_Beverages_1_.png&w=1920&q=75",
    },
    {
      key:2,
      img: "https://www.sparindia.com/_next/image?url=https%3A%2F%2Fmcprod.sparindia.com%2Fmedia%2Fwysiwyg%2Fjune-theme%2Fmobile%2FDairy_Frozen_s_1_.png&w=1920&q=75",
    },
    {
      key:3,
      img: "https://www.sparindia.com/_next/image?url=https%3A%2F%2Fmcprod.sparindia.com%2Fmedia%2Fwysiwyg%2Fjune-theme%2Fmobile%2FSnacks_Beverages_1_.png&w=1920&q=75",
    },
    {
      key:4,
      img: "https://www.sparindia.com/_next/image?url=https%3A%2F%2Fmcprod.sparindia.com%2Fmedia%2Fwysiwyg%2Fjune-theme%2Fmobile%2FHair_Face_Skincare_1_.png&w=1920&q=75",
    },
    {
      key:5,
      img: "https://www.sparindia.com/_next/image?url=https%3A%2F%2Fmcprod.sparindia.com%2Fmedia%2Fwysiwyg%2Fjune-theme%2Fmobile%2FDairy_Frozen_s_1_.png&w=1920&q=75",
    },
  ];

  export const Mega_Offer = "https://mcprod.sparindia.com/media/wysiwyg/72-hours/7days-Mahasavings.svg";



export  const catObj = [
    {
      name: "Ghee & Vanaspati",
      url_key: "ghee-vanaspati",
      uid: "MzE=",
      id: 31,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Ghee___Vanaspati.png",
      include_in_menu: 1,
      product_count: 27,
      offer:true
    },
    {
      name: "Organic Food",
      url_key: "organic-food",
      uid: "NTY1",
      id: 565,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Organic_Food.png",
      include_in_menu: 1,
      product_count: 164,
    },
    {
      name: "Flours",
      url_key: "flours",
      uid: "NTcx",
      id: 571,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Flours.png",
      include_in_menu: 1,
      product_count: 143,
    },
    {
      name: "Rice & Rice Products",
      url_key: "rice-rice-products",
      uid: "NTc3",
      id: 577,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Rice___Rice_Products.png",
      include_in_menu: 1,
      product_count: 146,
      offer:true
    },
    {
      name: "Pulses",
      url_key: "pulses",
      uid: "NTk4",
      id: 598,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Pulses.png",
      include_in_menu: 1,
      product_count: 59,
    },
    {
      name: "DAL",
      url_key: "dal",
      uid: "NjA0",
      id: 604,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dal.png",
      include_in_menu: 1,
      product_count: 33,
    },
    {
      name: "Masala & Spices",
      url_key: "masala-spices",
      uid: "NjM0",
      id: 634,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Masala___Spices.png",
      include_in_menu: 1,
      product_count: 533,
      offer:true
    },
    {
      name: "Salt / Sugar / Jaggery",
      url_key: "salt-sugar-jaggery",
      uid: "NjUy",
      id: 652,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Salt_Sugar_Jaggery.png",
      include_in_menu: 1,
      product_count: 74,
    },
    {
      name: "Cooking Oil",
      url_key: "cooking-oil",
      uid: "NjY3",
      id: 667,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Cooking_Oil.png",
      include_in_menu: 1,
      product_count: 147,
    },
    {
      name: "Dry Fruits",
      url_key: "dry-fruits",
      uid: "Njc2",
      id: 676,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dry_Fruits.png",
      include_in_menu: 1,
      product_count: 203,
    },
    {
      name: "Ghee & Vanaspati",
      url_key: "ghee-vanaspati",
      uid: "MzE=",
      id: 31,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Ghee___Vanaspati.png",
      include_in_menu: 1,
      product_count: 27,
    },
    {
      name: "Organic Food",
      url_key: "organic-food",
      uid: "NTY1",
      id: 565,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Organic_Food.png",
      include_in_menu: 1,
      product_count: 164,
    },
    {
      name: "Flours",
      url_key: "flours",
      uid: "NTcx",
      id: 571,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Flours.png",
      include_in_menu: 1,
      product_count: 143,
    },
    {
      name: "Rice & Rice Products",
      url_key: "rice-rice-products",
      uid: "NTc3",
      id: 577,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Rice___Rice_Products.png",
      include_in_menu: 1,
      product_count: 146,
    },
    {
      name: "Pulses",
      url_key: "pulses",
      uid: "NTk4",
      id: 598,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Pulses.png",
      include_in_menu: 1,
      product_count: 59,
    },
    {
      name: "DAL",
      url_key: "dal",
      uid: "NjA0",
      id: 604,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dal.png",
      include_in_menu: 1,
      product_count: 33,
    },
    {
      name: "Masala & Spices",
      url_key: "masala-spices",
      uid: "NjM0",
      id: 634,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Masala___Spices.png",
      include_in_menu: 1,
      product_count: 533,
    },
    {
      name: "Salt / Sugar / Jaggery",
      url_key: "salt-sugar-jaggery",
      uid: "NjUy",
      id: 652,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Salt_Sugar_Jaggery.png",
      include_in_menu: 1,
      product_count: 74,
      offer:true
    },
    {
      name: "Cooking Oil",
      url_key: "cooking-oil",
      uid: "NjY3",
      id: 667,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Cooking_Oil.png",
      include_in_menu: 1,
      product_count: 147,
    },
    {
      name: "Dry Fruits",
      url_key: "dry-fruits",
      uid: "Njc2",
      id: 676,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dry_Fruits.png",
      include_in_menu: 1,
      product_count: 203,
    },
    {
      name: "Ghee & Vanaspati",
      url_key: "ghee-vanaspati",
      uid: "MzE=",
      id: 31,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Ghee___Vanaspati.png",
      include_in_menu: 1,
      product_count: 27,
    },
    {
      name: "Organic Food",
      url_key: "organic-food",
      uid: "NTY1",
      id: 565,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Organic_Food.png",
      include_in_menu: 1,
      product_count: 164,
    },
    {
      name: "Flours",
      url_key: "flours",
      uid: "NTcx",
      id: 571,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Flours.png",
      include_in_menu: 1,
      product_count: 143,
      offer:true
    },
    {
      name: "Rice & Rice Products",
      url_key: "rice-rice-products",
      uid: "NTc3",
      id: 577,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Rice___Rice_Products.png",
      include_in_menu: 1,
      product_count: 146,
    },
    {
      name: "Pulses",
      url_key: "pulses",
      uid: "NTk4",
      id: 598,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Pulses.png",
      include_in_menu: 1,
      product_count: 59,
    },
    {
      name: "DAL",
      url_key: "dal",
      uid: "NjA0",
      id: 604,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dal.png",
      include_in_menu: 1,
      product_count: 33,
    },
    {
      name: "Masala & Spices",
      url_key: "masala-spices",
      uid: "NjM0",
      id: 634,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Masala___Spices.png",
      include_in_menu: 1,
      product_count: 533,
    },
    {
      name: "Salt / Sugar / Jaggery",
      url_key: "salt-sugar-jaggery",
      uid: "NjUy",
      id: 652,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Salt_Sugar_Jaggery.png",
      include_in_menu: 1,
      product_count: 74,
    },
    {
      name: "Cooking Oil",
      url_key: "cooking-oil",
      uid: "NjY3",
      id: 667,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Cooking_Oil.png",
      include_in_menu: 1,
      product_count: 147,
      offer:true
    },
    {
      name: "Dry Fruits",
      url_key: "dry-fruits",
      uid: "Njc2",
      id: 676,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dry_Fruits.png",
      include_in_menu: 1,
      product_count: 203,
    },
    {
      name: "Ghee & Vanaspati",
      url_key: "ghee-vanaspati",
      uid: "MzE=",
      id: 31,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Ghee___Vanaspati.png",
      include_in_menu: 1,
      product_count: 27,
    },
    {
      name: "Organic Food",
      url_key: "organic-food",
      uid: "NTY1",
      id: 565,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Organic_Food.png",
      include_in_menu: 1,
      product_count: 164,
    },
    {
      name: "Flours",
      url_key: "flours",
      uid: "NTcx",
      id: 571,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Flours.png",
      include_in_menu: 1,
      product_count: 143,
    },
    {
      name: "Rice & Rice Products",
      url_key: "rice-rice-products",
      uid: "NTc3",
      id: 577,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Rice___Rice_Products.png",
      include_in_menu: 1,
      product_count: 146,
    },
    {
      name: "Pulses",
      url_key: "pulses",
      uid: "NTk4",
      id: 598,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Pulses.png",
      include_in_menu: 1,
      product_count: 59,
    },
    {
      name: "DAL",
      url_key: "dal",
      uid: "NjA0",
      id: 604,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dal.png",
      include_in_menu: 1,
      offer:true,
      product_count: 33,
    },
    {
      name: "Masala & Spices",
      url_key: "masala-spices",
      uid: "NjM0",
      id: 634,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Masala___Spices.png",
      include_in_menu: 1,
      product_count: 533,
    },
    {
      name: "Salt / Sugar / Jaggery",
      url_key: "salt-sugar-jaggery",
      uid: "NjUy",
      id: 652,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Salt_Sugar_Jaggery.png",
      include_in_menu: 1,
      product_count: 74,
    },
    {
      name: "Cooking Oil",
      url_key: "cooking-oil",
      uid: "NjY3",
      id: 667,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Cooking_Oil.png",
      include_in_menu: 1,
      product_count: 147,
    },
    {
      name: "Dry Fruits",
      url_key: "dry-fruits",
      uid: "Njc2",
      id: 676,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dry_Fruits.png",
      include_in_menu: 1,
      product_count: 203,
    },
    {
      name: "Ghee & Vanaspati",
      url_key: "ghee-vanaspati",
      uid: "MzE=",
      id: 31,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Ghee___Vanaspati.png",
      include_in_menu: 1,
      product_count: 27,
    },
    {
      name: "Organic Food",
      url_key: "organic-food",
      uid: "NTY1",
      id: 565,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Organic_Food.png",
      include_in_menu: 1,
      product_count: 164,
    },
    {
      name: "Flours",
      url_key: "flours",
      uid: "NTcx",
      id: 571,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Flours.png",
      include_in_menu: 1,
      product_count: 143,
    },
    {
      name: "Rice & Rice Products",
      url_key: "rice-rice-products",
      uid: "NTc3",
      id: 577,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Rice___Rice_Products.png",
      include_in_menu: 1,
      product_count: 146,
      offer:true
    },
    {
      name: "Pulses",
      url_key: "pulses",
      uid: "NTk4",
      id: 598,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Pulses.png",
      include_in_menu: 1,
      product_count: 59,
    },
    {
      name: "DAL",
      url_key: "dal",
      uid: "NjA0",
      id: 604,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dal.png",
      include_in_menu: 1,
      product_count: 33,
    },
    {
      name: "Masala & Spices",
      url_key: "masala-spices",
      uid: "NjM0",
      id: 634,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Masala___Spices.png",
      include_in_menu: 1,
      product_count: 533,
    },
    {
      name: "Salt / Sugar / Jaggery",
      url_key: "salt-sugar-jaggery",
      uid: "NjUy",
      id: 652,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Salt_Sugar_Jaggery.png",
      include_in_menu: 1,
      product_count: 74,
    },
    {
      name: "Cooking Oil",
      url_key: "cooking-oil",
      uid: "NjY3",
      id: 667,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Cooking_Oil.png",
      include_in_menu: 1,
      product_count: 147,
    },
    {
      name: "Dry Fruits",
      url_key: "dry-fruits",
      uid: "Njc2",
      id: 676,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dry_Fruits.png",
      include_in_menu: 1,
      product_count: 203,
    },
    {
      name: "Ghee & Vanaspati",
      url_key: "ghee-vanaspati",
      uid: "MzE=",
      id: 31,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Ghee___Vanaspati.png",
      include_in_menu: 1,
      product_count: 27,
    },
    {
      name: "Organic Food",
      url_key: "organic-food",
      uid: "NTY1",
      id: 565,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Organic_Food.png",
      include_in_menu: 1,
      product_count: 164,
    },
    {
      name: "Flours",
      url_key: "flours",
      uid: "NTcx",
      id: 571,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Flours.png",
      include_in_menu: 1,
      product_count: 143,
    },
    {
      name: "Rice & Rice Products",
      url_key: "rice-rice-products",
      uid: "NTc3",
      id: 577,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Rice___Rice_Products.png",
      include_in_menu: 1,
      product_count: 146,
    },
    {
      name: "Pulses",
      url_key: "pulses",
      uid: "NTk4",
      id: 598,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Pulses.png",
      include_in_menu: 1,
      product_count: 59,
    },
    {
      name: "DAL",
      url_key: "dal",
      uid: "NjA0",
      id: 604,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dal.png",
      include_in_menu: 1,
      product_count: 33,
    },
    {
      name: "Masala & Spices",
      url_key: "masala-spices",
      uid: "NjM0",
      id: 634,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Masala___Spices.png",
      include_in_menu: 1,
      product_count: 533,
    },
    {
      name: "Salt / Sugar / Jaggery",
      url_key: "salt-sugar-jaggery",
      uid: "NjUy",
      id: 652,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Salt_Sugar_Jaggery.png",
      include_in_menu: 1,
      product_count: 74,
    },
    {
      name: "Cooking Oil",
      url_key: "cooking-oil",
      uid: "NjY3",
      id: 667,
      level: 3,
      image:
        "https://mcprod.sparindia.com/media/catalog/category/Cooking_Oil.png",
      include_in_menu: 1,
      product_count: 147,
    },
    {
      name: "Dry Fruits",
      url_key: "dry-fruits",
      uid: "Njc2",
      id: 676,
      level: 3,
      image: "https://mcprod.sparindia.com/media/catalog/category/Dry_Fruits.png",
      include_in_menu: 1,
      product_count: 203,
    },
  ];